Feat/euichang/band setting
woomurf/bandCloneCoding pull request #37
Opened 2022-08-15 14:04 UTC by Ohneul

쓰지않는 기능 제거
설정 화면의 회원 탈퇴, 밴드 관리(이미지 제외) 기능 구현(ui 관련된 작업은 이미지 기능까지 끝내고 할 예정)
멤버 정보보기 소스 클린업

2022-08-15 14:08 UTC, woomurf commented on backend/routes/user.js
> +router.delete('/:id', async (req, res) => {
authValidate middleware 필요해보임.

2022-08-15 14:24 UTC, woomurf commented on backend/routes/user.js
> +router.delete('/:id', async (req, res) => {
authValidator middleware 필요해보여요

2022-08-20 12:38 UTC, Ohneul commented on backend/routes/user.js
> +router.delete('/:id', async (req, res) => {
authValidator 추가하였습니다.

2022-08-21 13:30 UTC, woomurf commented on frontend/src/component/SettingBody.js
> +                  <button className="settingButton" onClick={this.props.onClick.bind(this, informations.title)}>
이거 onClick보다 조금 더 알아보기 쉬운 함수 이름으로 하면 어떨까요?

2022-08-21 13:34 UTC, woomurf commented on frontend/src/popup/GroupInfoPopup.js
> +      profileImageUrl : ""
이거 profileImageUrl을 `""` 으로 넣으면 이미지가 없어집니다. 그.. 이미지 변경 부분을 나중에 작업하려고 처리해둔거면 요기 주석처리 하면 어떨까요~?

2022-08-21 13:39 UTC, woomurf commented on frontend/src/popup/GroupInfoPopup.js
> +  const modifyGroup = async (id, modName, modDes) => {
이거 함수에서 name, description, profileImageUrl 정도 수정할 수 있을 것 같은데, 무조건 모든 인자를 넣어야하는 구조 같습니다.
인자를 객체로 넘겨주면 일부분만 넣을 수 있는데요. 어떠세요?

```
modifyGroup({ id, name, description, profileImageUrl })
```

2022-08-21 13:43 UTC, woomurf commented on frontend/src/popup/MemberInfoPopup.js
> +              src={props.memberInfo.profileImageUrl || DefaultProfileImage}
이거 `props.memberInfo.` 로 계속 쓰고있는데 변수로 하나 선언해서 쓰는 것도 좋아보입니다.

```
const memberInfo = props.memberInfo 
or 
const { id, name, email, birth, profileImageUrl } = props.memberInfo
```

요런 느낌?

2022-08-21 13:45 UTC, woomurf commented on frontend/src/screen/MainScreen.js
> +      groupId : 1,
minor) 이거 groupId 어차피 고정일거 그냥 state 말고 상수로 선언하는 건 어떠신가유?

2022-08-21 13:51 UTC, woomurf commented on frontend/src/screen/MainScreen.js
> +            if (result === 'success') {
요거 조건문이 왜있는..?

2022-08-21 13:52 UTC, woomurf commented on frontend/src/screen/MainScreen.js
> +              this.props.onClick("");
이것도 `onClick` 이라서 어떤 함수인지 바로 모르겟음 ㅠㅠ

2022-08-21 13:54 UTC, woomurf commented on frontend/src/screen/SettingFrame.js
> +                  onClick={this.props.onClick.bind(this, "로그아웃")}>
props.onClick...!!!

2022-08-21 13:55 UTC, woomurf commented on frontend/src/screen/SettingFrame.js
> +                onClick={this.props.onClick}
여기도!

2022-08-21 13:55 UTC, woomurf requested changes
코멘트 남겼습니다~

2022-08-21 13:59 UTC, Ohneul commented on frontend/src/screen/MainScreen.js
> +      groupId : 1,
마지막까지 한개로 끝나겠지만 ID 라는 것인점에서 따로 선언한 상태입니다. 인지한 상태로 놔두겠습니다!

2022-08-22 12:10 UTC, Ohneul commented on frontend/src/component/SettingBody.js
> +                  <button className="settingButton" onClick={this.props.onClick.bind(this, informations.title)}>
다음 브런치에서 수정 예정

2022-08-22 12:11 UTC, Ohneul commented on frontend/src/screen/MainScreen.js
> +              this.props.onClick("");
다음 브런치에서 수정 예정

2022-08-22 12:11 UTC, Ohneul commented on frontend/src/screen/SettingFrame.js
> +                  onClick={this.props.onClick.bind(this, "로그아웃")}>
다음 브런치에서 수정 예정

2022-08-22 12:11 UTC, Ohneul commented on frontend/src/screen/SettingFrame.js
> +                onClick={this.props.onClick}
다음 브런치에서 수정 예정

2022-08-22 12:12 UTC, Ohneul commented on frontend/src/popup/GroupInfoPopup.js
> +      profileImageUrl : ""
임시 수정완료입니다!

2022-08-22 12:19 UTC, Ohneul commented on frontend/src/popup/MemberInfoPopup.js
> +              src={props.memberInfo.profileImageUrl || DefaultProfileImage}
수정완료입니다~ grorupInfoPopup도 같은 맥락으로 수정했습니다.

2022-08-22 12:26 UTC, Ohneul commented on frontend/src/screen/MainScreen.js
> +            if (result === 'success') {
LoginScreen 부분 무지성하게 복사해서 써버렸네요 수정 했습니다.

2022-08-22 12:40 UTC, Ohneul commented on frontend/src/popup/GroupInfoPopup.js
> +  const modifyGroup = async (id, modName, modDes) => {
체크해보니 인자를 넘길 필요가 없다고 느껴서 없앴습니다.

2022-08-26 13:03 UTC, woomurf approved these changes
LGTM!

2022-08-27 12:28 UTC, merged