Feature/youngjun/register logic
woomurf/bandCloneCoding pull request #6
Opened 2022-02-03 13:55 UTC by selp0100

### **추가사항**

- Postbox Component
- PictureCollect Component
- Main_Lside Component
- PostUploadbox Component
- SearchBox Component

### **수정사항**

-  RegisterPopup : "Id" "pwd" "birth" "name" Validation Form

2022-02-03 15:04 UTC, Ohneul commented
Request 올릴 때
추가 사항
-
-
-
수정 사항
-
-
-
이런식으로 하는 것을 추천합니다

2022-02-03 15:04 UTC, woomurf requested changes

2022-02-03 15:04 UTC, woomurf commented on frontend/src/component/Main_Rside.js
> +                <img alt="" className="pictureSort" src={this.props.pictureCollect} id="pictureSort"/>
같은 이미지를 반복해서 넣을거면, `const images = [src1, src2, src3 ...]` 으로 바꾼다음에 반복문을 이용해서 div를 그리는건 어떨까요오오ㅗㅇ

2022-02-03 15:04 UTC, woomurf commented on frontend/src/component/Postbox.js
> +import SM from '../image/See More.png';
이거 `See More.png` 이름을 `See_More.png` 으로 바꾸는건 어떨까요오오ㅗㅇ (space 삭제)

2022-02-03 15:04 UTC, woomurf commented on frontend/src/screen/PostScreen.js
> +import taco from '../image/Taco.png';
이미지 이름 대문자로 갈거면 여기도 `Taco` 로 통일하면 어떨까요오오오ㅗㅇㅇ

2022-02-03 15:04 UTC, woomurf commented on frontend/src/screen/PostScreen.js
> +            <Post
여기 postlist도 다 `<Post>` 컴포넌트를 일일히 작성하는 것이 아니라, dummy data를 list로 만들고, 반복문을 사용해 그려주면 좋을 것 같습니다.

포인트는 더미데이터마다 포함하는 내용이 다르다! (이미지가 있는 녀석도 있고, 없는 녀석도 있을 것임)

ex)` const dummyData = [{ userName: '권영준', profileImage: taco}, {username: '우현웅', text: '크림파스타 냠냠', ...} ]`

2022-02-03 15:04 UTC, woomurf commented on frontend/src/screen/PostScreen.js
> +var now = new Date();
여기 날짜 계산하는 부분을 함수로 만들고, 컴포넌트 안에 넣으면 좋을 것 같습니다.

2022-02-12 07:55 UTC, woomurf approved these changes
LGTM!

2022-02-12 07:55 UTC, merged